POST http://localhost:5000/api/stories
Content-Type: application/json
user-id: 60c72b2f9d1d802d08f12345

{
  "privacy": "public",
  "media": [
    {
      "mediaUrl": "https://example.com/photo1.jpg",
      "mediaType": "image"
    }
  ]
}

###

POST http://localhost:5000/api/language/request-change
Content-Type: application/json

{
  "userId": "user_123",
  "language": "fr"
}

###

POST http://localhost:5000/api/language/verify-otp
Content-Type: application/json

{
  "userId": "user_123",
  "otp": "507547",
  "newLanguage": "fr"
}